### ISSUE TITLE
English/Times New Roman font

### ISSUE THREAD

**Issue by conky2** [ShabadOS/Shabad-OS#1]
Can this app be reconfigured to use English/Times New Roman Font in place of Gurmukhi?  I have a database of English translations I would like to use.  Thanks!

**Comment by bhajneet** [comment]
Yes, you can do that. Another option would be to replace the english translation column with your own in the database.

**Comment by conky2** [comment]
Great, thanks -- this is very cool!  

One follow-up: Is the database schema available?  I didn't see it here: https://github.com/ShabadOS/Database

**Comment by bhajneet** [comment]
If you're using windows, you can download it from the site, then go into the folder where it's installed. There you can edit includes/data with an sqlite editor to use your translations. You can also edit the css file to use Times New Roman in the `.gurmukhifont` class.

We will finish re-doing the english translations by end of this year. If you'd like to help out, please let us know or star the [database repo](https://github.com/ShabadOS/Database).

**Comment by conky2** [comment]
I cannot read Gurmukhi, but I would be happy to help with any editing for
the English translations once the Gurmukhi to English is done.  I'm a
graduate student and writing/editing is something I do a lot of.

Separately, are you available as an independent contractor?  I'd like to
repurpose this project for another use case and figured I would ask you if
it were something of interest.

**Comment by bhajansweet** [comment]
Could you give us some more information on your use case? If it's something that will be useful for others as well, we can consider adding it to this project.

**Comment by bhajneet** [comment]
Then we're most likely not interested. Without any further information we cannot be 100%. If you'd like to share anything else in private, please leave an email address.
